Set Shellcheck level to style (#42)

diff --git a/finbotctl b/finbotctl
--- a/finbotctl
+++ b/finbotctl
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-function help {
+function usage {
   echo "finbot control utility"
   echo
   echo "Usage:"
@@ -9,14 +9,24 @@ function help {
   echo "  init: "
   echo "  start: "
   echo "  stop: "
+  echo "  restart: "
 }
 
-command=$1
+command="${1}"
 if [[ -z "${command}" ]]
 then
-  help
+  usage
+  exit 1
+fi
+
+command_script="./tools/finbotctl-${command}"
+if [[ ! -f "${command_script}" ]]
+then
+  echo "!! invalid command: ${command}"
+  echo
+  usage
   exit 1
 fi
 
 shift 1
-./tools/finbotctl-${command} "$@"
+"./tools/finbotctl-${command}" "$@"
